# Generated by Django 4.2.3 on 2023-08-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cadastro', '0002_alter_evento_data_fim_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='materia',
        ),
    ]
